## Veri Setini Tanıma

Veri Setini Tanıma
Amaç:

1. Veri setinin genel yapısını tanımak ve temel özelliklerini incelemek
2. Veri analizi öncesi gerekli ilk kontrolleri uygulamak

Adımlar:

1. Veri setini yükle
2. Veri setinin ilk ve son satırlarını incele
3. Veri setinin boyutunu ve sütunlarını kontrol etmek
4. Veri setinin genel bilgisini incele
5. Özet istatistikleri görüntüle
6. Veri tiplerini kontrol et
7. Sayısal ve kategorik sütunları ayırmak
8. Benzersiz (unique) değer sayılarını incelemek

In [1]:
import pandas as pd

In [2]:
# 1. Veri setini yükleme
df = pd.read_csv("e_ticaret_veri_seti.csv")

In [4]:
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03

In [5]:
# 2. Veri setinin ilk ve son satırlarını incele
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03

In [8]:
df.shape # Data frame shape komutu bir Tuple verir.

(1428, 18)

##### Dataframe shape 0.index'i alındığında satır, 1.index alındığında sütun sayısını verir.

In [6]:
# 3. Veri setinin boyutunu ve sütunlarını kontrol etme
satir_sayisi = df.shape[0]
satir_sayisi

1428

In [9]:
sutun_sayisi = df.shape[1]
sutun_sayisi

18

In [11]:
# sütun isimleri
for i, sutun in enumerate(df.columns, start = 1): ## Index 0'dam başlar ancak numaralandırma 1'den başlasın diye start=1 dedil
 print(f"{i}. {sutun}")

1. siparis_id
2. musteri_id
3. siparis_tarihi
4. sehir
5. bolge
6. kategori
7. urun_adi
8. adet
9. birim_fiyat
10. indirim_orani
11. kargo_ucreti
12. odeme_turu
13. musteri_tipi
14. teslimat_gunu
15. musteri_puani
16. iade_durumu
17. kar_marji_orani
18. toplam_tutar

##### Sipariş Tarihi DateTime olması gerekirken Object olduğu görülür. Değiştirilmesi gerek, ayrıca null değerler var.

In [12]:
# 4. Veri setinin genel bilgisini inceleme
df.info() # sütun isimlerini, veri tiplerini, missing value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   siparis_id       1428 non-null   object
 1   musteri_id       1428 non-null   object
 2   siparis_tarihi   1428 non-null   object
 3   sehir            1403 non-null   object
 4   bolge            1428 non-null   object
 5   kategori         1428 non-null   object
 6   urun_adi         1428 non-null   object
 7   adet             1428 non-null   int64
 8   birim_fiyat      1428 non-null   float64
 9   indirim_orani    1412 non-null   float64
 10  kargo_ucreti     1428 non-null   float64
 11  odeme_turu       1393 non-null   object
 12  musteri_tipi     1386 non-null   object
 13  teslimat_gunu    1400 non-null   float64
 14  musteri_puani    1372 non-null   float64
 15  iade_durumu      1428 non-null   object
 16  kar_marji_orani  1428 non-null   float64
 17  toplam_tutar     1428 non-null   float64
dtypes: float64(7), int64(1), object(10)
memory usage: 200.9+ KB

##### Sayısal Sütunların Temel İstatistik Özellikleri

In [15]:
# Özet istatistikleri görüntüleme
df.describe() # sayısal sütunlar için temel istatistikler

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar
count,1428.000000,1428.000000,1412.000000,1428.000000,1400.000000,1372.000000,1428.000000,1428.000000
mean,2.136555,658.477654,0.052054,39.725140,3.370714,4.002187,0.302799,1370.590336
std,2.015770,1042.414639,0.060115,14.185017,1.825990,1.096707,0.069795,2961.689500
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000
25%,1.000000,199.185000,0.000000,29.900000,2.000000,3.000000,0.244750,323.855000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,669.135000
75%,3.000000,819.177500,0.100000,49.900000,4.000000,5.000000,0.362000,1390.950000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,7.000000,0.420000,63870.200000

In [16]:
# 6. Veri tiplerini kontrol etme
df.dtypes

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [18]:
# 7. Sayısal ve kategorik sütunların ayrılması
# sayısal: float64, int64
sayisal_sutunlar = df.select_dtypes(include=["int64", "float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [19]:
# 8. Benzersiz (unique) değer sayılarını incelemek
for sutun in df.columns:
  print(f"{sutun}: {df[sutun].nunique()}")

siparis_id: 1400
musteri_id: 422
siparis_tarihi: 1398
sehir: 19
bolge: 6
kategori: 15
urun_adi: 30
adet: 10
birim_fiyat: 1381
indirim_orani: 5
kargo_ucreti: 5
odeme_turu: 12
musteri_tipi: 7
teslimat_gunu: 11
musteri_puani: 8
iade_durumu: 2
kar_marji_orani: 241
toplam_tutar: 1397

## Kayıp Veri (Missing Value)

Amaç:

1. Eksik veri tespiti ve farklı eksik veri çözüm yöntemlerini uygulamak
2. Kullanılacak güncel veri setini kaydetme

Adımlar:

1. Veri setini yükleme
2. Eksik verileri tespit etme
3. Eksik veri oranlarını hesaplama
4. Eksik veri içeren satırları incele
5. Eksik verileri silmek
6. Sayısal eksik verileri ortalama ile doldur
7. Sayısal eksik verileri medyan ile doldur
8. Sayısal eksik verileri mod ile doldur
9. Kategorik eksik verileri mod ile doldur
10. Kategorik eksik verileri sabit bir değer ile doldurmak
11. Eğitimde kullanılacak olan güncel veri setini oluştur
12. Düzenlenmiş veri setini kaydet

In [21]:
import pandas as pd

In [22]:
# 1. veri setini yükle
df = pd.read_csv("e_ticaret_veri_seti.csv")

In [23]:
# 2. eksik verileri tespit etme
df.isnull().sum()

siparis_id          0
musteri_id          0
siparis_tarihi      0
sehir              25
bolge               0
kategori            0
urun_adi            0
adet                0
birim_fiyat         0
indirim_orani      16
kargo_ucreti        0
odeme_turu         35
musteri_tipi       42
teslimat_gunu      28
musteri_puani      56
iade_durumu         0
kar_marji_orani     0
toplam_tutar        0
dtype: int64

In [24]:
# 3. eksik veri oranlarını hesapla
eksik_sayilari = df.isnull().sum()
eksik_oranlari = 100 * (eksik_sayilari / len(df))
eksik_oranlari

siparis_id         0.000000
musteri_id         0.000000
siparis_tarihi     0.000000
sehir              1.750700
bolge              0.000000
kategori           0.000000
urun_adi           0.000000
adet               0.000000
birim_fiyat        0.000000
indirim_orani      1.120448
kargo_ucreti       0.000000
odeme_turu         2.450980
musteri_tipi       2.941176
teslimat_gunu      1.960784
musteri_puani      3.921569
iade_durumu        0.000000
kar_marji_orani    0.000000
toplam_tutar       0.000000
dtype: float64

In [25]:
# 4. eksik veri içeren satırları incele
eksik_veri_olan_satirlar = df[df.isnull().any(axis = 1)]
eksik_veri_olan_satirlar.head(10)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
19,SIP100677,MUS1148,2024-07-11 16:24:00,Adana,Akdeniz,Spor,Dambıl Seti,4,1517.65,0.0,29.9,Kapıda Ödeme,Mevcut,3.0,NaN,Hayır,0.311,6100.50
33,SIP101126,MUS1406,2024-09-11 20:05:00,Mersin,Akdeniz,Elektronik,Bluetooth Hoparlör,1,1159.89,0.1,39.9,Kredi Kartı,NaN,2.0,4.0,Hayır,0.204,1083.80
50,SIP101040,MUS1386,2025-04-01 09:30:00,Trabzon,Karadeniz,Spor,Dambıl Seti,1,1554.15,0.0,49.9,Banka Kartı,NaN,4.0,5.0,Hayır,0.217,1604.05
60,SIP100890,MUS1271,2024-11-07 19:47:00,İzmir,Ege,Kitap,Girişimcilik,4,216.38,NaN,49.9,Kredi Kartı,Yeni,1.0,3.0,Hayır,0.199,915.42
61,SIP101317,MUS1060,2024-09-05 20:49:00,NaN,Akdeniz,Ev ve Yaşam,Saklama Kutusu,1,233.63,0.1,29.9,Dijital Cüzdan,Yeni,5.0,2.0,Hayır,0.385,240.17
70,SIP100715,MUS1033,2024-11-10 21:50:00,İstanbul,Marmara,Ev ve Yaşam,Termos,1,552.05,0.0,39.9,NaN,Mevcut,2.0,3.0,Hayır,0.185,591.95
82,SIP100807,MUS1431,2025-01-07 14:12:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,451.28,0.0,49.9,Kredi Kartı,NaN,4.0,5.0,Hayır,0.315,501.18
84,SIP100679,MUS1310,2024-05-20 18:51:00,İzmir,Ege,Ev ve Yaşam,Termos,2,477.62,0.0,49.9,Kredi Kartı,Mevcut,NaN,4.0,Hayır,0.323,1005.14
86,SIP101071,MUS1131,2024-09-18 12:24:00,NaN,İç Anadolu,Elektronik,Powerbank,1,816.74,0.0,39.9,Banka Kartı,Yeni,3.0,5.0,Hayır,0.301,856.64
92,SIP101366,MUS1347,2025-03-04 14:00:00,Bursa,Marmara,Ev ve Yaşam,Organizer,1,272.40,0.0,29.9,Kredi Kartı,Mevcut,1.0,NaN,Hayır,0.212,302.30

In [28]:
# 5. Eksik verileri silme
df_silinen = df.dropna() # dropna ile eksik değer içeren satırları veri setinden çıkarttık

In [29]:
df_silinen

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,SIP101222,MUS1440,2025-05-14 09:21:00,Bursa,Marmara,Spor,Dambıl Seti,1,1488.18,0.00,29.9,Kredi Kartı,Mevcut,3.0,4.0,Hayır,0.189,1518.08
1423,SIP101093,MUS1187,2024-06-08 20:42:00,İstanbul,Marmara,Spor,Yoga Matı,1,772.23,0.00,29.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.275,802.13
1424,SIP101193,MUS1297,2025-11-06 08:17:00,Gaziantep,Güneydoğu Anadolu,Spor,Suluk,2,187.03,0.00,59.9,Kredi Kartı,Yeni,2.0,4.0,Evet,0.243,433.96
1426,SIP101060,MUS1189,2025-04-19 21:52:00,Kocaeli,Marmara,Kitap,Veri Bilimi 101,2,248.55,0.05,59.9,banka karti,Yeni,4.0,3.0,Hayır,0.373,532.14
1427,SIP100642,MUS1289,2024-09-22 16:36:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,424.84,0.20,0.0,Dijital Cüzdan,Yeni,2.0,4.0,Hayır,0.317,339.87

In [30]:
df_silinen.shape

(1239, 18)

In [31]:
# 6. Sayısal eksik verilerin ortalama ile doldurulması
df_ortalama = df.copy()
sayisal_sutunlar = df_ortalama.select_dtypes(include = ["int64", "float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [32]:
for sutun in sayisal_sutunlar:
  df_ortalama[sutun] = df_ortalama[sutun].fillna(df_ortalama[sutun].mean())

In [33]:
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [34]:
# 7. sayısal eksik verileri medyan ile doldurma
df_medyan = df.copy()
for sutun in sayisal_sutunlar:
  df_medyan[sutun] = df_medyan[sutun].fillna(df_medyan[sutun].median())
df_medyan[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [35]:
# 8. Sayısal eksik verileri mod ile doldurma
df_mod_sayisal = df.copy()
for sutun in sayisal_sutunlar:
  mod_degeri = df_mod_sayisal[sutun].mode()[0] ## Mod liste içerisinde değer ürettiğinden 0.indexini alacağız.
  df_mod_sayisal[sutun] = df_mod_sayisal[sutun].fillna(mod_degeri)
df_mod_sayisal[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [36]:
# 9. kategorik eksik verileri mod ile doldurma
df_mod_kategorik = df.copy()
kategorik_sutunlar = df_mod_kategorik.select_dtypes(include = ["object"]).columns
kategorik_sutunlar

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [37]:
for sutun in kategorik_sutunlar:
  mod_degeri = df_mod_kategorik[sutun].mode()[0]
  df_mod_kategorik[sutun] = df_mod_kategorik[sutun].fillna(mod_degeri)

In [38]:
df_mod_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [39]:
# 10. kategorik eksik verileri sabit bir değer ile dolduralım
df_sabit_kategorik = df.copy()

for sutun in kategorik_sutunlar:
  df_sabit_kategorik[sutun] = df_sabit_kategorik[sutun].fillna("Bilinmiyor")

In [40]:
df_sabit_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [42]:
# 11. Kullanacağımız güncel veri seti
# sayısal eksik verileri medyan ile doldur
# kategorik eksik verileri mod ile doldur

In [43]:
df_guncel = df.copy()

In [44]:
for sutun in sayisal_sutunlar:
  df_guncel[sutun] = df_guncel[sutun].fillna(df_guncel[sutun].median())

In [45]:
for sutun in kategorik_sutunlar:
  mod_degeri = df_guncel[sutun].mode()[0]
  df_guncel[sutun] = df_guncel[sutun].fillna(mod_degeri)

In [46]:
df_guncel.isnull().sum()

siparis_id         0
musteri_id         0
siparis_tarihi     0
sehir              0
bolge              0
kategori           0
urun_adi           0
adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
odeme_turu         0
musteri_tipi       0
teslimat_gunu      0
musteri_puani      0
iade_durumu        0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [47]:
# 12. düzenlenmiş veri setini kaydedelim
kayit_dosyasi = "e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv"
df_guncel.to_csv(kayit_dosyasi, index = False)

## Veri Tipleri ve Dönüşümler

Amaç:

1. Veri setindeki sütunların veri tiplerini incelemek ve gerekli dönüşümleri uygulamak
2. Kullanılacak güncel veri setini oluşturarak kaydetmek

Adımlar:

1. Veri setini yüklemek
2. Veri tiplerini incelemek
3. Sayısal, kategorik ve tarih sütunlarını belirlemek
4. Sipariş tarihi sütununu datetime tipine dönüştürmek (string -> datetime)
5. Tarih sütunundan yeni özellikler üretmek (Feature extraction)
6. Kategorik sütunları category tipine dönüştürmek (string -> category)
7. Dönüşüm sonrası veri tipi kontrol etmek
8. Güncellenmiş veri setini kaydetmek

In [48]:
import pandas as pd

In [49]:
# 1. veri setini yüklemek
df = pd.read_csv("e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv")

In [50]:
# 2. Veri tiplerini incelemek
df.dtypes

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [51]:
# 3. Sayısal, kategorik ve tarih sütunlarını belirlemek
sayisal_sutunlar = df.select_dtypes(include = ["int64", "float64"]).columns.tolist()
sayisal_sutunlar

['adet',
 'birim_fiyat',
 'indirim_orani',
 'kargo_ucreti',
 'teslimat_gunu',
 'musteri_puani',
 'kar_marji_orani',
 'toplam_tutar']

In [52]:
kategorik_sutunlar = df.select_dtypes(include = ["object"]).columns.tolist()
kategorik_sutunlar

['siparis_id',
 'musteri_id',
 'siparis_tarihi',
 'sehir',
 'bolge',
 'kategori',
 'urun_adi',
 'odeme_turu',
 'musteri_tipi',
 'iade_durumu']

In [53]:
# 4. Sipariş tarihi sütununu datetime tipine dönüştürmek (string -> datetime)
df["siparis_tarihi"] = pd.to_datetime(df["siparis_tarihi"])
df["siparis_tarihi"].dtype

dtype('<M8[ns]')

In [54]:
df.dtypes

siparis_id                 object
musteri_id                 object
siparis_tarihi     datetime64[ns]
sehir                      object
bolge                      object
kategori                   object
urun_adi                   object
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu                 object
musteri_tipi               object
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                object
kar_marji_orani           float64
toplam_tutar              float64
dtype: object

In [55]:
# 5. Tarih sütunundan yeni özelliklerin üretilmesi
# zaman bazlı analizlerde yıl, ay, gün ve hafta günü bilgilerini üretiyoruz.
df["siparis_yili"] = df["siparis_tarihi"].dt.year
df["siparis_ayi"] = df["siparis_tarihi"].dt.month
df["siparis_gunu"] = df["siparis_tarihi"].dt.day
df["haftanin_gunu"] = df["siparis_tarihi"].dt.day_name()
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,...,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,...,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,...,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday

In [56]:
# 6. kategorik sütunları category tipine dönüştürme
kategorik_donusum_sutunlari = [
    "sehir",
    "kategori",
    "urun_adi",
    "odeme_turu",
    "musteri_tipi",
    "haftanin_gunu"
]

In [57]:
for sutun in kategorik_donusum_sutunlari:
  df[sutun] = df[sutun].astype("category")

In [58]:
# 7. Dönüşüm sonrası veri tiplerini tekrar kontrol et
df.dtypes

siparis_id                 object
musteri_id                 object
siparis_tarihi     datetime64[ns]
sehir                    category
bolge                      object
kategori                 category
urun_adi                 category
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu               category
musteri_tipi             category
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                object
kar_marji_orani           float64
toplam_tutar              float64
siparis_yili                int32
siparis_ayi                 int32
siparis_gunu                int32
haftanin_gunu            category
dtype: object

In [59]:
# 8. Güncellenmiş veri setini kaydedelim
df.to_csv("e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv")

## Tekrarlayan ve Tutarsız Kayıtlar

Amaç:

1. Veri setindeki tekrarlayan ve tutarsız kayıtları tespit edip temizlemek
2. Eğitimde kullanılacak güncel veri setini kaydet

Adımlar:

1. Veri setini yüklemek
2. Tekrarlayan kayıtları tespit etmek
3. Tekrarlayan kayıtları incelemek
4. Tekrarlayan kayıtları temizlemek
5. Tutarsız kategorik değerleri incelemek
6. Şehir sütunundaki tutarsız değerleri düzeltmek
7. Kategori sütunundaki tutarsız değerleri düzeltmek
8. Ödeme türü sütunundaki tutarsız değerleri düzeltmek
9. Müşteri tipi sütunundaki tutarsız değerleri düzeltmek
10. Mantıksal olarak hatalı kayıtları incele
11. Mantıksal olarak hatalı kayıtları temizleme
12. Güncellenmiş veri setini kaydet

In [63]:
import pandas as pd

In [64]:
# 1. Veri setini yükleme
df = pd.read_csv("e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv")
df.shape

(1428, 22)

In [65]:
# 2. tekrarlayan kayıtları tespit et
tekrarlayan_kayitlar = df[df.duplicated()]
len(tekrarlayan_kayitlar)

28

#### Not: Aynı olanları göstermez. Bir tane gösterir.

In [66]:
# 3. tekrarlayan kayıtları incele
tekrarlayan_kayitlar.head(5)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
174,SIP100479,MUS1099,2025-06-10 20:32:00,İstanbul,Marmara,Kozmetik,Güneş Kremi,3,455.19,0.00,...,Yeni,1.0,5.0,Hayır,0.200,1415.47,2025,6,10,Tuesday
315,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
324,SIP100533,MUS1128,2024-11-19 14:22:00,Trabzon,Karadeniz,Kitap,Python Notları,2,225.82,0.00,...,Yeni,4.0,5.0,Hayır,0.234,491.54,2024,11,19,Tuesday
613,SIP100725,MUS1146,2025-05-24 10:10:00,Kocaeli,Marmara,Kitap,Zaman Yönetimi,2,154.18,0.05,...,Yeni,3.0,5.0,Hayır,0.385,342.84,2025,5,24,Saturday
637,SIP100940,MUS1032,2025-03-25 20:06:00,Samsun,Karadeniz,Kozmetik,Serum,1,507.46,0.15,...,Mevcut,3.0,4.0,Evet,0.402,471.24,2025,3,25,Tuesday

In [67]:
# 4. tekrarlayan kayıtları temizle
df = df.drop_duplicates()
df.shape

(1400, 22)

In [68]:
# 5. tutarsız değerlerin incelenmesi
df["sehir"].unique()
# 'istanbul', 'ankara', 'Istanbul', 'gaziantep', 'Izmir

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun', 'istanbul', 'ankara', 'Istanbul',
       'gaziantep', 'Izmir'], dtype=object)

In [69]:
df["kategori"].unique()
# 'Ofis', 'ofis', 'Elektronik ',  'Elektronik', 'spor', 'kozmetık', 'ev ve yaşam', 'kitap', 'Kozmetik ', 'elektronik', 'Ev&Yaşam'

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'ofis',
       'Ev ve Yaşam', 'Elektronik ', 'spor', 'kozmetık', 'ev ve yaşam',
       'kitap', 'Kozmetik ', 'elektronik', 'Ev&Yaşam'], dtype=object)

In [70]:
df["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT', 'Kart', 'kredi kartı', 'dijital cüzdan', 'eft',
       'banka karti', 'Kapida Odeme', 'Havale'], dtype=object)

In [71]:
df["musteri_tipi"].unique()

array(['Yeni', 'VIP', 'Mevcut', 'yeni', 'Vip', 'mevcut', 'vip'],
      dtype=object)

In [72]:
# yardımcı fonksiyon: metinleri normalize edelim
# büyük küçük harf dönüşümleri, boşlukların kaldırılması, Türkçe karakter kaynaklı farkların düzenlenmesi
def metin_normalize_et(series):

  return(
      series.astype(str)
      .str.strip()
      .str.lower()
      .str.replace("i̇", "i", regex=False)
      .str.replace("ı", "i", regex=False)
      .str.replace("ö", "o", regex=False)
      .str.replace("ü", "u", regex=False)
      .str.replace("ç", "c", regex=False)
      .str.replace("ş", "s", regex=False)
      .str.replace("ğ", "g", regex=False)
  )

In [73]:
# 6. şehir sütunundaki tutarsız değerleri düzeltme
df["sehir"] = metin_normalize_et(df["sehir"])
df["sehir"].unique()

array(['istanbul', 'gaziantep', 'kayseri', 'antalya', 'konya', 'ankara',
       'bursa', 'trabzon', 'adana', 'mersin', 'kocaeli', 'izmir',
       'eskisehir', 'samsun'], dtype=object)

In [74]:
sehir_duzeltme_haritasi = {
    "istanbul": "İstanbul",
    "ankara": "Ankara",
    "izmir": "İzmir",
    "antalya": "Antalya",
    "konya": "Konya",
    "bursa": "Bursa",
    "adana": "Adana",
    "gaziantep": "Gaziantep",
    "mersin": "Mersin",
    "kayseri": "Kayseri",
    "eskisehir": "Eskişehir",
    "samsun": "Samsun",
    "trabzon": "Trabzon",
    "kocaeli": "Kocaeli"
}
df["sehir"] = df["sehir"].replace(sehir_duzeltme_haritasi)
df["sehir"].unique()

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun'], dtype=object)

In [75]:
# 7. kategori sütunundaki tutarsız değerleri düzeltme
df["kategori"] = metin_normalize_et(df["kategori"])
df["kategori"].unique()

array(['kozmetik', 'spor', 'kitap', 'elektronik', 'ofis', 'ev ve yasam',
       'ev&yasam'], dtype=object)

In [76]:
kategori_duzeltme_haritasi = {
    "elektronik": "Elektronik",
    "kitap": "Kitap",
    "kozmetik": "Kozmetik",
    "kozmetık": "Kozmetik",
    "spor": "Spor",
    "ev yasam": "Ev Yaşam",
    "ev ve yasam": "Ev Yaşam",
    "ev&yasam": "Ev Yaşam",
    "ofis": "Ofis"
}
df["kategori"] = df["kategori"].replace(kategori_duzeltme_haritasi)
df["kategori"].unique()

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'Ev Yaşam'],
      dtype=object)

In [77]:
# 8. ödeme türü sütunundaki tutarsız değerleri düzeltelim
df["odeme_turu"] = metin_normalize_et(df["odeme_turu"])
df["odeme_turu"].unique()

array(['kredi karti', 'banka karti', 'kapida odeme', 'dijital cuzdan',
       'havale/eft', 'kart', 'eft', 'havale'], dtype=object)

In [78]:
odeme_turu_duzeltme_haritasi = {
    "kredi karti": "Kredi Kartı",
    "kart": "Kredi Kartı",
    "banka karti": "Banka Kartı",
    "dijital cuzdan": "Dijital Cüzdan",
    "kapida odeme": "Kapıda Ödeme",
    "havale": "Havale/EFT",
    "eft": "Havale/EFT",
    "havale/eft": "Havale/EFT"
}
df["odeme_turu"] = df["odeme_turu"].replace(odeme_turu_duzeltme_haritasi)
df["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT'], dtype=object)

In [79]:
# 9. müşteri tipi sütunundaki tutarsız değerleri düzeltelim
df["musteri_tipi"] = metin_normalize_et(df["musteri_tipi"])
df["musteri_tipi"].unique()

array(['yeni', 'vip', 'mevcut'], dtype=object)

In [80]:
musteri_tipi_duzeltme_haritasi = {
    "mevcut": "Mevcut",
    "yeni": "Yeni",
    "vip": "VIP"
}
df["musteri_tipi"] = df["musteri_tipi"].replace(musteri_tipi_duzeltme_haritasi)
df["musteri_tipi"].unique()

array(['Yeni', 'VIP', 'Mevcut'], dtype=object)

In [81]:
df["musteri_tipi"].value_counts()

musteri_tipi
Mevcut    716
Yeni      520
VIP       164
Name: count, dtype: int64

In [82]:
# 10. mantıksal olarak hatalı kayıtları inceleme
# negatif yada anlamsız değerler bazı kayıtlarda veri kalitesini düşürebilir
hatali_kayitlar = df[
    (df["adet"] <= 0) |
    (df["toplam_tutar"] <= 0) |
    (df["birim_fiyat"] <= 0) |
    (df["teslimat_gunu"] < 0) |
    (df["musteri_puani"] < 0) |
    (df["musteri_puani"] > 5)
]
len(hatali_kayitlar)

2

In [83]:
pd.set_option("display.max_columns", None)
hatali_kayitlar

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
609,SIP100095,MUS1165,2025-10-12 21:31:00,İstanbul,Marmara,Kozmetik,Şampuan,2,190.17,0.10,0.0,Dijital Cüzdan,Mevcut,3.0,6.0,Hayır,0.416,342.31,2025,10,12,Sunday
1008,SIP101290,MUS1225,2024-01-16 21:46:00,Kocaeli,Marmara,Kozmetik,Yüz Temizleme Jeli,2,303.82,0.05,29.9,Kredi Kartı,Yeni,5.0,7.0,Evet,0.287,607.16,2024,1,16,Tuesday

In [84]:
# 11. mantıksal hataları temizleyelim
df = df[
    (df["adet"] > 0) &
    (df["toplam_tutar"] > 0) &
    (df["birim_fiyat"] > 0) &
    (df["teslimat_gunu"] >= 0) &
    (df["musteri_puani"] >= 0) &
    (df["musteri_puani"] <= 5)
]
df.shape

(1398, 22)

In [85]:
# 12. güncellenmiş verinini kaydedilmesi
df.to_csv("e_ticaret_veri_seti_tekrarlayan_kayitlar_duzenlendi.csv")

## Aykırı Değerler (Outliers)

Amaç:

1. Veri setindeki aykırı değerlerin tespit edilmesi ve incelenmesi
2. Aykırı değerleri temizleyerek güncel veri setinin oluşturulması
Adımlar:

1. Veri setini yükle
2. Sayısal sütunları belirle
3. Sayısal sütunların özet istatistiklerini hesapla
4. IQR ile aykırı değer sınırlarını hesapla
5. Aykırı değer içeren kayıtları tespit etmek
6. Aykırı değer sayılarını sütun bazında incelemek
7. Aykırı değer içeren kayıtları veri setinden temizlemek
8. Temizlenmiş veri setini kaydetmek

In [89]:
import pandas as pd

In [90]:
# 1. veri setini yüklemek
df = pd.read_csv("e_ticaret_veri_seti_tekrarlayan_kayitlar_duzenlendi.csv")

In [91]:
# 2. sayısal sütunların belirlenmesi
sayisal_sutunlar = df.select_dtypes(include = ["int64", "float64"]).columns.tolist()
sayisal_sutunlar

['adet',
 'birim_fiyat',
 'indirim_orani',
 'kargo_ucreti',
 'teslimat_gunu',
 'musteri_puani',
 'kar_marji_orani',
 'toplam_tutar',
 'siparis_yili',
 'siparis_ayi',
 'siparis_gunu']

In [92]:
# 3. sayısal sütunların özet istatistiklerini inceleyelim
df[sayisal_sutunlar].describe()

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu
count,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000
mean,2.143062,660.712818,0.051717,39.728398,3.355508,3.997854,0.302446,1377.934642,2024.528612,6.394134,15.655222
std,2.031849,1051.014558,0.059681,14.188925,1.771142,1.071193,0.069861,2988.042747,0.499359,3.455187,8.720828
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000,2024.000000,1.000000,1.000000
25%,1.000000,198.855000,0.000000,29.900000,2.000000,4.000000,0.243250,327.190000,2024.000000,3.000000,8.000000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,670.965000,2025.000000,6.000000,16.000000
75%,3.000000,817.335000,0.100000,49.900000,4.000000,5.000000,0.362000,1393.250000,2025.000000,9.000000,23.000000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,5.000000,0.420000,63870.200000,2025.000000,12.000000,31.000000

In [93]:
"""birim_fiyat
  IQR = Q3(75%) - Q1(25%)
      = 817 - 198 = 619
  Üst sınır = Q3 + k*IQR
  Alt sınır = Q1 - k*IQR
    k = 1 olsun
    Üst sınır = 817 + 619 = 1436
    Alt sınır = 198 - 619 = -421
  Outlier = üst sınır ve alt sınır dışında kalan örnekler
"""

'birim_fiyat\n  IQR = Q3(75%) - Q1(25%)\n      = 817 - 198 = 619\n  Üst sınır = Q3 + k*IQR\n  Alt sınır = Q1 - k*IQR\n    k = 1 olsun\n    Üst sınır = 817 + 619 = 1436\n    Alt sınır = 198 - 619 = -421\n  Outlier = üst sınır ve alt sınır dışında kalan örnekler\n'

In [94]:
# 4. IQR ile aykırı değer sınırlarını hesaplama
aykiri_sinirlar = {}

for sutun in sayisal_sutunlar:

  q1 = df[sutun].quantile(0.25)
  q3 = df[sutun].quantile(0.75)

  iqr = q3 - q1
  alt_sinir = q1 - 1.5 * iqr
  ust_sinir = q3 + 1.5 * iqr

  aykiri_sinirlar[sutun] = {
      "q1": q1,
      "q3": q3,
      "iqr": iqr,
      "alt_sinir": alt_sinir,
      "ust_sinir": ust_sinir
  }

In [95]:
aykiri_sinirlar

{'adet': {'q1': 1.0,
  'q3': 3.0,
  'iqr': 2.0,
  'alt_sinir': -2.0,
  'ust_sinir': 6.0},
 'birim_fiyat': {'q1': 198.85500000000002,
  'q3': 817.335,
  'iqr': 618.48,
  'alt_sinir': -728.865,
  'ust_sinir': 1745.055},
 'indirim_orani': {'q1': 0.0,
  'q3': 0.1,
  'iqr': 0.1,
  'alt_sinir': -0.15000000000000002,
  'ust_sinir': 0.25},
 'kargo_ucreti': {'q1': 29.9,
  'q3': 49.9,
  'iqr': 20.0,
  'alt_sinir': -0.10000000000000142,
  'ust_sinir': 79.9},
 'teslimat_gunu': {'q1': 2.0,
  'q3': 4.0,
  'iqr': 2.0,
  'alt_sinir': -1.0,
  'ust_sinir': 7.0},
 'musteri_puani': {'q1': 4.0,
  'q3': 5.0,
  'iqr': 1.0,
  'alt_sinir': 2.5,
  'ust_sinir': 6.5},
 'kar_marji_orani': {'q1': 0.24325,
  'q3': 0.362,
  'iqr': 0.11875,
  'alt_sinir': 0.06512500000000002,
  'ust_sinir': 0.540125},
 'toplam_tutar': {'q1': 327.19,
  'q3': 1393.25,
  'iqr': 1066.06,
  'alt_sinir': -1271.8999999999999,
  'ust_sinir': 2992.34},
 'siparis_yili': {'q1': 2024.0,
  'q3': 2025.0,
  'iqr': 1.0,
  'alt_sinir': 2022.5,
  'ust_sinir': 2026.5},
 'siparis_ayi': {'q1': 3.0,
  'q3': 9.0,
  'iqr': 6.0,
  'alt_sinir': -6.0,
  'ust_sinir': 18.0},
 'siparis_gunu': {'q1': 8.0,
  'q3': 23.0,
  'iqr': 15.0,
  'alt_sinir': -14.5,
  'ust_sinir': 45.5}}

In [96]:
# 5. aykırı değer içeren kayıtları tespit et
aykiri_maskesi = pd.Series(False, index = df.index)

for sutun in sayisal_sutunlar:
  alt_sinir = aykiri_sinirlar[sutun]["alt_sinir"]
  ust_sinir = aykiri_sinirlar[sutun]["ust_sinir"]

  sutun_maskesi = (df[sutun] < alt_sinir) | (df[sutun] > ust_sinir)
  aykiri_maskesi = aykiri_maskesi | sutun_maskesi

In [97]:
aykiri_kayitlar = df[aykiri_maskesi]
aykiri_kayitlar

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
6,SIP101351,MUS1011,2025-02-27 11:35:00,İstanbul,Marmara,Ofis,Mouse Pad,3,169.47,0.05,29.9,Havale/EFT,VIP,3.0,2.0,Evet,0.382,512.89,2025,2,27,Thursday
7,SIP101172,MUS1357,2024-07-22 13:26:00,Ankara,İç Anadolu,Ofis,Mekanik Klavye,3,2344.47,0.00,59.9,Kredi Kartı,Mevcut,3.0,4.0,Hayır,0.312,7093.31,2024,7,22,Monday
8,SIP100779,MUS1354,2025-12-05 11:19:00,İstanbul,Marmara,Kitap,Python Notları,4,219.14,0.00,29.9,Kredi Kartı,Yeni,18.0,5.0,Evet,0.408,906.46,2025,12,5,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387,SIP100177,MUS1075,2024-01-29 13:59:00,Trabzon,Karadeniz,Ofis,Mekanik Klavye,3,2169.51,0.00,39.9,Kredi Kartı,Mevcut,1.0,4.0,Hayır,0.273,6548.43,2024,1,29,Monday
1389,SIP100056,MUS1238,2024-04-19 20:27:00,Ankara,İç Anadolu,Kitap,Veri Bilimi 101,2,255.70,0.05,59.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.247,545.73,2024,4,19,Friday
1390,SIP101279,MUS1149,2024-08-24 08:38:00,Ankara,İç Anadolu,Elektronik,Akıllı Saat,4,3074.80,0.15,39.9,Banka Kartı,Yeni,4.0,5.0,Hayır,0.414,10494.22,2024,8,24,Saturday
1393,SIP101093,MUS1187,2024-06-08 20:42:00,İstanbul,Marmara,Spor,Yoga Matı,1,772.23,0.00,29.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.275,802.13,2024,6,8,Saturday
1395,SIP101210,MUS1122,2025-03-07 09:07:00,İstanbul,Marmara,Elektronik,Webcam,4,894.47,0.10,49.9,Kredi Kartı,Mevcut,3.0,5.0,Hayır,0.355,3269.99,2025,3,7,Friday

##### Not: Müşteri puanı için aykırı değer bulmak mantıklı değildir.

In [98]:
# 6. aykırı değer sayılarını sütun bazında incele
for sutun in sayisal_sutunlar:

  alt_sinir = aykiri_sinirlar[sutun]["alt_sinir"]
  ust_sinir = aykiri_sinirlar[sutun]["ust_sinir"]

  aykiri_sayi = ((df[sutun] < alt_sinir) | (df[sutun] > ust_sinir)).sum()
  print(f"{sutun}: {aykiri_sayi}")

adet: 6
birim_fiyat: 92
indirim_orani: 0
kargo_ucreti: 0
teslimat_gunu: 5
musteri_puani: 151
kar_marji_orani: 0
toplam_tutar: 134
siparis_yili: 0
siparis_ayi: 0
siparis_gunu: 0

### 1428 veri, 1095'e düştü.

In [99]:
# 7. aykırı değer içeren kayıtları veri setinden temizleme
df_temiz = df[~aykiri_maskesi].copy()
df_temiz.shape

(1095, 22)

In [100]:
# 8. temizlenmiş veri setini kaydet
df_temiz.to_csv("e_ticaret_veri_seti_aykiri_degerler_duzenlendi.csv")

## Kategorik Veri Analizi